import Capacitor
import CoreBluetooth

/// Native BLE bridge for the Precept Motion Service (see docs/wearable-protocol.md).
///
/// The web layer owns all protocol logic; this plugin only moves bytes:
///   - scans for a watch advertising the Precept service UUID
///   - subscribes to IMU notifications and relays each 16-byte packet as hex
///   - writes command/time-sync bytes (generated by the web layer) verbatim
///   - reads the battery level
///
/// Events emitted to the web layer:
///   - "preceptPacket"       { packet: string /* 32 hex chars */ }
///   - "preceptBattery"      { battery: number }
///   - "preceptDisconnected" {}
@objc(PreceptBlePlugin)
public class PreceptBlePlugin: CAPPlugin, CBCentralManagerDelegate, CBPeripheralDelegate {

    private enum Precept {
        static let service = CBUUID(string: "D5F2A1A0-3F1E-4B6E-9C2E-7F3A8B4C5D6E")
        static let imu = CBUUID(string: "D5F2A1A1-3F1E-4B6E-9C2E-7F3A8B4C5D6E")
        static let command = CBUUID(string: "D5F2A1A2-3F1E-4B6E-9C2E-7F3A8B4C5D6E")
        static let battery = CBUUID(string: "D5F2A1A3-3F1E-4B6E-9C2E-7F3A8B4C5D6E")
        static let sessionData = CBUUID(string: "D5F2A1A5-3F1E-4B6E-9C2E-7F3A8B4C5D6E")

        // Offline session commands (docs/wearable-protocol.md §12.1).
        static let commandListSessions: UInt8 = 0x10
        static let commandRequestSession: UInt8 = 0x11
        static let commandDeleteSession: UInt8 = 0x12
        static let commandDeleteAll: UInt8 = 0x13

        // Session Data chunk framing.
        static let chunkFlagFirst: UInt8 = 0x80
        static let chunkFlagLast: UInt8 = 0x40
        static let chunkFlagError: UInt8 = 0x20
        static let sessionTimeoutSeconds = 120
    }

    private var centralManager: CBCentralManager?
    private var peripheral: CBPeripheral?
    private var commandCharacteristic: CBCharacteristic?
    private var lastBatteryLevel: Int?
    private var pendingConnectCall: CAPPluginCall?
    private var connectTimeout: DispatchWorkItem?
    private var scanning = false

    // Session Data transfer state (one transfer at a time).
    private var sessionDataCharacteristic: CBCharacteristic?
    private var sessionChunks = Data()
    private var sessionHasFirst = false
    private var sessionCompletion: ((String) -> Void)?
    private var sessionErrorHandler: ((Error) -> Void)?
    private var sessionTimeout: DispatchWorkItem?

    override public func load() {
        super.load()
        centralManager = CBCentralManager(delegate: self, queue: nil)
    }

    // MARK: - Plugin methods

    @objc func connect(_ call: CAPPluginCall) {
        guard let centralManager else {
            call.reject("Bluetooth is unavailable")
            return
        }
        guard centralManager.state == .poweredOn else {
            call.reject("Bluetooth is powered off. Enable Bluetooth in Settings and try again.")
            return
        }
        if let peripheral, peripheral.state == .connected {
            call.resolve(connectResult(peripheral))
            return
        }
        pendingConnectCall = call
        call.keepAlive = true
        startScan(centralManager)
    }

    @objc func sendCommand(_ call: CAPPluginCall) {
        guard let value = call.getString("value") else {
            call.reject("Missing command value")
            return
        }
        guard let peripheral, peripheral.state == .connected, let commandCharacteristic else {
            call.reject("Not connected to a watch")
            return
        }
        guard let data = Data(hexString: value) else {
            call.reject("Command value is not valid hex")
            return
        }
        peripheral.writeValue(data, for: commandCharacteristic, type: .withoutResponse)
        call.resolve()
    }

    @objc func disconnect(_ call: CAPPluginCall) {
        cancelScan()
        cancelSessionTransfer()
        if let peripheral {
            centralManager?.cancelPeripheralConnection(peripheral)
        }
        call.resolve()
    }

    // MARK: - Offline session sync (§12.1)

    @objc func listSessions(_ call: CAPPluginCall) {
        beginSessionTransfer(command: Data([Precept.commandListSessions]), call: call)
    }

    @objc func fetchSession(_ call: CAPPluginCall) {
        guard let index = call.getInt("index"), index >= 0 else {
            call.reject("Missing session index")
            return
        }
        beginSessionTransfer(command: Data([Precept.commandRequestSession, UInt8(index & 0xff)]), call: call)
    }

    @objc func deleteSession(_ call: CAPPluginCall) {
        guard let index = call.getInt("index"), index >= 0 else {
            call.reject("Missing session index")
            return
        }
        beginSessionTransfer(command: Data([Precept.commandDeleteSession, UInt8(index & 0xff)]), call: call)
    }

    @objc func clearSessions(_ call: CAPPluginCall) {
        beginSessionTransfer(command: Data([Precept.commandDeleteAll]), call: call)
    }

    /// Writes one session command and resolves `{ json }` with the fully
    /// reassembled Session Data message. One transfer at a time, 120 s timeout.
    private func beginSessionTransfer(command: Data, call: CAPPluginCall) {
        guard let peripheral, peripheral.state == .connected, let commandCharacteristic else {
            call.reject("Not connected to a watch")
            return
        }
        guard sessionDataCharacteristic != nil else {
            call.reject("Session data characteristic unavailable on the watch")
            return
        }
        guard sessionCompletion == nil else {
            call.reject("A session transfer is already in progress")
            return
        }

        sessionChunks = Data()
        sessionHasFirst = false
        call.keepAlive = true

        sessionCompletion = { json in
            var result = JSObject()
            result["json"] = json
            call.resolve(result)
        }
        sessionErrorHandler = { error in
            call.reject(error.localizedDescription)
        }

        let timeout = DispatchWorkItem { [weak self] in
            self?.failSessionTransfer(message: "Session transfer timed out")
        }
        sessionTimeout = timeout
        DispatchQueue.main.asyncAfter(deadline: .now() + Double(Precept.sessionTimeoutSeconds), execute: timeout)

        peripheral.writeValue(command, for: commandCharacteristic, type: .withoutResponse)
    }

    // MARK: - Scanning / connecting

    private func startScan(_ centralManager: CBCentralManager) {
        guard !scanning else { return }
        scanning = true
        centralManager.scanForPeripherals(withServices: [Precept.service], options: nil)
        connectTimeout = DispatchWorkItem { [weak self] in
            guard let self else { return }
            self.scanning = false
            centralManager.stopScan()
            if let call = self.pendingConnectCall {
                self.pendingConnectCall = nil
                call.reject("No Precept watch found within 20 seconds")
            }
        }
        DispatchQueue.main.asyncAfter(deadline: .now() + 20, execute: connectTimeout!)
    }

    private func cancelScan() {
        connectTimeout?.cancel()
        connectTimeout = nil
        if scanning {
            centralManager?.stopScan()
            scanning = false
        }
    }

    private func connectResult(_ peripheral: CBPeripheral) -> JSObject {
        var result = JSObject()
        result["deviceName"] = peripheral.name
        if let lastBatteryLevel {
            result["battery"] = lastBatteryLevel
        }
        return result
    }

    // MARK: - CBCentralManagerDelegate

    public func centralManagerDidUpdateState(_ central: CBCentralManager) {
        // State changes are surfaced as rejected connect() calls; nothing to do
        // here because a pending call is rejected at call time if not powered on.
    }

    public func centralManager(_ central: CBCentralManager, didDiscover peripheral: CBPeripheral, advertisementData: [String: Any], rssi RSSI: NSNumber) {
        cancelScan()
        self.peripheral = peripheral
        peripheral.delegate = self
        central.connect(peripheral, options: nil)
    }

    public func centralManager(_ central: CBCentralManager, didConnect peripheral: CBPeripheral) {
        peripheral.discoverServices([Precept.service])
    }

    public func centralManager(_ central: CBCentralManager, didFailToConnect peripheral: CBPeripheral, error: Error?) {
        pendingConnectCall?.reject(error?.localizedDescription ?? "Failed to connect to the watch")
        pendingConnectCall = nil
        self.peripheral = nil
    }

    public func centralManager(_ central: CBCentralManager, didDisconnectPeripheral peripheral: CBPeripheral, error: Error?) {
        self.peripheral = nil
        commandCharacteristic = nil
        sessionDataCharacteristic = nil
        if sessionCompletion != nil || sessionErrorHandler != nil {
            finishSessionTransfer(error: NSError(domain: "PreceptBle", code: -1, userInfo: [NSLocalizedDescriptionKey: "Watch disconnected during session transfer"]))
        }
        notifyListeners("preceptDisconnected", data: [:])
    }

    // MARK: - CBPeripheralDelegate

    public func peripheral(_ peripheral: CBPeripheral, didDiscoverServices error: Error?) {
        guard let service = peripheral.services?.first(where: { $0.uuid == Precept.service }) else {
            pendingConnectCall?.reject("Precept Motion Service not found on the watch")
            pendingConnectCall = nil
            centralManager?.cancelPeripheralConnection(peripheral)
            return
        }
        peripheral.discoverCharacteristics([Precept.imu, Precept.command, Precept.battery, Precept.sessionData], for: service)
    }

    public func peripheral(_ peripheral: CBPeripheral, didDiscoverCharacteristicsFor service: CBService, error: Error?) {
        guard let characteristics = service.characteristics else { return }
        for characteristic in characteristics {
            switch characteristic.uuid {
            case Precept.imu:
                peripheral.setNotifyValue(true, for: characteristic)
            case Precept.command:
                commandCharacteristic = characteristic
            case Precept.battery:
                peripheral.readValue(for: characteristic)
            case Precept.sessionData:
                sessionDataCharacteristic = characteristic
                peripheral.setNotifyValue(true, for: characteristic)
            default:
                break
            }
        }
    }

    public func peripheral(_ peripheral: CBPeripheral, didUpdateNotificationStateFor characteristic: CBCharacteristic, error: Error?) {
        guard characteristic.uuid == Precept.imu else { return }
        if let error {
            pendingConnectCall?.reject(error.localizedDescription)
            pendingConnectCall = nil
            centralManager?.cancelPeripheralConnection(peripheral)
            return
        }
        let call = pendingConnectCall
        pendingConnectCall = nil
        call?.resolve(connectResult(peripheral))
    }

    public func peripheral(_ peripheral: CBPeripheral, didUpdateValueFor characteristic: CBCharacteristic, error: Error?) {
        guard let value = characteristic.value else { return }
        if characteristic.uuid == Precept.sessionData {
            if let error {
                failSessionTransfer(message: error.localizedDescription)
            } else {
                handleSessionData(value)
            }
            return
        }
        switch characteristic.uuid {
        case Precept.imu:
            notifyListeners("preceptPacket", data: ["packet": value.hexString])
        case Precept.battery:
            let level = value.isEmpty ? 0 : Int(value[0])
            lastBatteryLevel = level
            notifyListeners("preceptBattery", data: ["battery": level])
        default:
            break
        }
    }

    // MARK: - Session Data reassembly (§12.1)

    /// Reassembles the chunked Session Data stream (flags byte + fragment),
    /// then resolves the pending call with the assembled JSON string.
    private func handleSessionData(_ data: Data) {
        guard data.count >= 1 else {
            finishSessionTransfer(error: NSError(domain: "PreceptBle", code: -1, userInfo: [NSLocalizedDescriptionKey: "Received an empty session chunk"]))
            return
        }
        let flags = data[data.startIndex]
        let fragment = data.dropFirst()

        if flags & Precept.chunkFlagError != 0 {
            let message = String(data: Data(fragment), encoding: .utf8)?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
            let text = message.isEmpty ? "Watch reported a session error" : "Watch error: \(message)"
            finishSessionTransfer(error: NSError(domain: "PreceptBle", code: -1, userInfo: [NSLocalizedDescriptionKey: text]))
            return
        }

        if flags & Precept.chunkFlagFirst != 0 {
            sessionChunks = Data()
            sessionHasFirst = true
        } else if !sessionHasFirst {
            finishSessionTransfer(error: NSError(domain: "PreceptBle", code: -1, userInfo: [NSLocalizedDescriptionKey: "Received a session chunk before the first chunk"]))
            return
        }

        sessionChunks.append(contentsOf: fragment)

        if flags & Precept.chunkFlagLast != 0 {
            guard let text = String(data: sessionChunks, encoding: .utf8) else {
                finishSessionTransfer(error: NSError(domain: "PreceptBle", code: -1, userInfo: [NSLocalizedDescriptionKey: "Session message was not valid UTF-8"]))
                return
            }
            let completion = sessionCompletion
            cancelSessionTransfer()
            completion?(text)
        }
    }

    private func failSessionTransfer(message: String) {
        finishSessionTransfer(error: NSError(domain: "PreceptBle", code: -1, userInfo: [NSLocalizedDescriptionKey: message]))
    }

    private func finishSessionTransfer(error: Error) {
        let handler = sessionErrorHandler
        cancelSessionTransfer()
        handler?(error)
    }

    private func cancelSessionTransfer() {
        sessionTimeout?.cancel()
        sessionTimeout = nil
        sessionCompletion = nil
        sessionErrorHandler = nil
        sessionChunks = Data()
        sessionHasFirst = false
    }
}

private extension Data {
    init?(hexString: String) {
        let normalized = hexString.replacingOccurrences(of: " ", with: "")
        guard normalized.count.isMultiple(of: 2) else { return nil }
        var bytes = [UInt8]()
        bytes.reserveCapacity(normalized.count / 2)
        var index = normalized.startIndex
        while index < normalized.endIndex {
            let next = normalized.index(index, offsetBy: 2)
            guard let byte = UInt8(normalized[index..<next], radix: 16) else { return nil }
            bytes.append(byte)
            index = next
        }
        self.init(bytes)
    }

    var hexString: String {
        map { String(format: "%02x", $0) }.joined()
    }
}
