import Capacitor
import CoreBluetooth

/// Native BLE bridge for the Precept Motion Service (see docs/wearable-protocol.md).
///
/// The web layer owns all protocol logic; this plugin only moves bytes:
///   - scans for a watch advertising the Precept service UUID
///   - subscribes to IMU notifications and relays each 16-byte packet as hex
///   - writes command/time-sync bytes (generated by the web layer) verbatim
///   - reads the battery level
///
/// Events emitted to the web layer:
///   - "preceptPacket"       { packet: string /* 32 hex chars */ }
///   - "preceptBattery"      { battery: number }
///   - "preceptDisconnected" {}
@objc(PreceptBlePlugin)
public class PreceptBlePlugin: CAPPlugin, CBCentralManagerDelegate, CBPeripheralDelegate {

    private enum Precept {
        static let service = CBUUID(string: "D5F2A1A0-3F1E-4B6E-9C2E-7F3A8B4C5D6E")
        static let imu = CBUUID(string: "D5F2A1A1-3F1E-4B6E-9C2E-7F3A8B4C5D6E")
        static let command = CBUUID(string: "D5F2A1A2-3F1E-4B6E-9C2E-7F3A8B4C5D6E")
        static let battery = CBUUID(string: "D5F2A1A3-3F1E-4B6E-9C2E-7F3A8B4C5D6E")
    }

    private var centralManager: CBCentralManager?
    private var peripheral: CBPeripheral?
    private var commandCharacteristic: CBCharacteristic?
    private var lastBatteryLevel: Int?
    private var pendingConnectCall: CAPPluginCall?
    private var connectTimeout: DispatchWorkItem?
    private var scanning = false

    override public func load() {
        super.load()
        centralManager = CBCentralManager(delegate: self, queue: nil)
    }

    // MARK: - Plugin methods

    @objc func connect(_ call: CAPPluginCall) {
        guard let centralManager else {
            call.reject("Bluetooth is unavailable")
            return
        }
        guard centralManager.state == .poweredOn else {
            call.reject("Bluetooth is powered off. Enable Bluetooth in Settings and try again.")
            return
        }
        if let peripheral, peripheral.state == .connected {
            call.resolve(connectResult(peripheral))
            return
        }
        pendingConnectCall = call
        call.keepAlive = true
        startScan(centralManager)
    }

    @objc func sendCommand(_ call: CAPPluginCall) {
        guard let value = call.getString("value") else {
            call.reject("Missing command value")
            return
        }
        guard let peripheral, peripheral.state == .connected, let commandCharacteristic else {
            call.reject("Not connected to a watch")
            return
        }
        guard let data = Data(hexString: value) else {
            call.reject("Command value is not valid hex")
            return
        }
        peripheral.writeValue(data, for: commandCharacteristic, type: .withoutResponse)
        call.resolve()
    }

    @objc func disconnect(_ call: CAPPluginCall) {
        cancelScan()
        if let peripheral {
            centralManager?.cancelPeripheralConnection(peripheral)
        }
        call.resolve()
    }

    // MARK: - Scanning / connecting

    private func startScan(_ centralManager: CBCentralManager) {
        guard !scanning else { return }
        scanning = true
        centralManager.scanForPeripherals(withServices: [Precept.service], options: nil)
        connectTimeout = DispatchWorkItem { [weak self] in
            guard let self else { return }
            self.scanning = false
            centralManager.stopScan()
            if let call = self.pendingConnectCall {
                self.pendingConnectCall = nil
                call.reject("No Precept watch found within 20 seconds")
            }
        }
        DispatchQueue.main.asyncAfter(deadline: .now() + 20, execute: connectTimeout!)
    }

    private func cancelScan() {
        connectTimeout?.cancel()
        connectTimeout = nil
        if scanning {
            centralManager?.stopScan()
            scanning = false
        }
    }

    private func connectResult(_ peripheral: CBPeripheral) -> JSObject {
        var result = JSObject()
        result["deviceName"] = peripheral.name
        if let lastBatteryLevel {
            result["battery"] = lastBatteryLevel
        }
        return result
    }

    // MARK: - CBCentralManagerDelegate

    public func centralManagerDidUpdateState(_ central: CBCentralManager) {
        // State changes are surfaced as rejected connect() calls; nothing to do
        // here because a pending call is rejected at call time if not powered on.
    }

    public func centralManager(_ central: CBCentralManager, didDiscover peripheral: CBPeripheral, advertisementData: [String: Any], rssi RSSI: NSNumber) {
        cancelScan()
        self.peripheral = peripheral
        peripheral.delegate = self
        central.connect(peripheral, options: nil)
    }

    public func centralManager(_ central: CBCentralManager, didConnect peripheral: CBPeripheral) {
        peripheral.discoverServices([Precept.service])
    }

    public func centralManager(_ central: CBCentralManager, didFailToConnect peripheral: CBPeripheral, error: Error?) {
        pendingConnectCall?.reject(error?.localizedDescription ?? "Failed to connect to the watch")
        pendingConnectCall = nil
        self.peripheral = nil
    }

    public func centralManager(_ central: CBCentralManager, didDisconnectPeripheral peripheral: CBPeripheral, error: Error?) {
        self.peripheral = nil
        commandCharacteristic = nil
        notifyListeners("preceptDisconnected", data: [:])
    }

    // MARK: - CBPeripheralDelegate

    public func peripheral(_ peripheral: CBPeripheral, didDiscoverServices error: Error?) {
        guard let service = peripheral.services?.first(where: { $0.uuid == Precept.service }) else {
            pendingConnectCall?.reject("Precept Motion Service not found on the watch")
            pendingConnectCall = nil
            centralManager?.cancelPeripheralConnection(peripheral)
            return
        }
        peripheral.discoverCharacteristics([Precept.imu, Precept.command, Precept.battery], for: service)
    }

    public func peripheral(_ peripheral: CBPeripheral, didDiscoverCharacteristicsFor service: CBService, error: Error?) {
        guard let characteristics = service.characteristics else { return }
        for characteristic in characteristics {
            switch characteristic.uuid {
            case Precept.imu:
                peripheral.setNotifyValue(true, for: characteristic)
            case Precept.command:
                commandCharacteristic = characteristic
            case Precept.battery:
                peripheral.readValue(for: characteristic)
            default:
                break
            }
        }
    }

    public func peripheral(_ peripheral: CBPeripheral, didUpdateNotificationStateFor characteristic: CBCharacteristic, error: Error?) {
        guard characteristic.uuid == Precept.imu else { return }
        if let error {
            pendingConnectCall?.reject(error.localizedDescription)
            pendingConnectCall = nil
            centralManager?.cancelPeripheralConnection(peripheral)
            return
        }
        let call = pendingConnectCall
        pendingConnectCall = nil
        call?.resolve(connectResult(peripheral))
    }

    public func peripheral(_ peripheral: CBPeripheral, didUpdateValueFor characteristic: CBCharacteristic, error: Error?) {
        guard let value = characteristic.value else { return }
        switch characteristic.uuid {
        case Precept.imu:
            notifyListeners("preceptPacket", data: ["packet": value.hexString])
        case Precept.battery:
            let level = value.isEmpty ? 0 : Int(value[0])
            lastBatteryLevel = level
            notifyListeners("preceptBattery", data: ["battery": level])
        default:
            break
        }
    }
}

private extension Data {
    init?(hexString: String) {
        let normalized = hexString.replacingOccurrences(of: " ", with: "")
        guard normalized.count.isMultiple(of: 2) else { return nil }
        var bytes = [UInt8]()
        bytes.reserveCapacity(normalized.count / 2)
        var index = normalized.startIndex
        while index < normalized.endIndex {
            let next = normalized.index(index, offsetBy: 2)
            guard let byte = UInt8(normalized[index..<next], radix: 16) else { return nil }
            bytes.append(byte)
            index = next
        }
        self.init(bytes)
    }

    var hexString: String {
        map { String(format: "%02x", $0) }.joined()
    }
}
